-- MySQL Script generated by MySQL Workbench
-- Fri Jan 17 15:54:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Xl3R7tru__asaas
-- -----------------------------------------------------
-- Stores all the charges and operations from the ASAAS customers.

-- -----------------------------------------------------
-- Schema Xl3R7tru__asaas
--
-- Stores all the charges and operations from the ASAAS customers.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Xl3R7tru__asaas` DEFAULT CHARACTER SET utf8 ;
USE `Xl3R7tru__asaas` ;

-- -----------------------------------------------------
-- Table `Xl3R7tru__asaas`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xl3R7tru__asaas`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `cpf` CHAR(11) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xl3R7tru__asaas`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xl3R7tru__asaas`.`payment_methods` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Connects with the charges table to attribute a payment method, such as credit card, bank slip, debit, etc.';


-- -----------------------------------------------------
-- Table `Xl3R7tru__asaas`.`charges_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xl3R7tru__asaas`.`charges_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Stores the current status of the charges, such as paid, expired, pending, etc.';


-- -----------------------------------------------------
-- Table `Xl3R7tru__asaas`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xl3R7tru__asaas`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Company which emits the charges';


-- -----------------------------------------------------
-- Table `Xl3R7tru__asaas`.`charges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xl3R7tru__asaas`.`charges` (
  `id` INT(9) ZEROFILL NOT NULL AUTO_INCREMENT,
  `due_date` DATETIME NOT NULL,
  `payment_date` DATETIME NULL,
  `value` FLOAT UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `companies_id` INT UNSIGNED NOT NULL,
  `customers_id` INT UNSIGNED NOT NULL,
  `payment_methods_id` INT UNSIGNED NOT NULL,
  `charges_status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_charges_customers_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_charges_payment_methods1_idx` (`payment_methods_id` ASC) VISIBLE,
  INDEX `fk_charges_charges_status1_idx` (`charges_status_id` ASC) VISIBLE,
  INDEX `fk_charges_companies1_idx` (`companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_charges_customers`
    FOREIGN KEY (`customers_id`)
    REFERENCES `Xl3R7tru__asaas`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charges_payment_methods1`
    FOREIGN KEY (`payment_methods_id`)
    REFERENCES `Xl3R7tru__asaas`.`payment_methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charges_charges_status1`
    FOREIGN KEY (`charges_status_id`)
    REFERENCES `Xl3R7tru__asaas`.`charges_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charges_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `Xl3R7tru__asaas`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Xl3R7tru__asaas`.`payment_methods`
-- -----------------------------------------------------
START TRANSACTION;
USE `Xl3R7tru__asaas`;
INSERT INTO `Xl3R7tru__asaas`.`payment_methods` (`id`, `description`) VALUES (1, 'Boleto bancário');
INSERT INTO `Xl3R7tru__asaas`.`payment_methods` (`id`, `description`) VALUES (2, 'Cartão de crédito');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Xl3R7tru__asaas`.`charges_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `Xl3R7tru__asaas`;
INSERT INTO `Xl3R7tru__asaas`.`charges_status` (`id`, `description`) VALUES (1, 'Pendente');
INSERT INTO `Xl3R7tru__asaas`.`charges_status` (`id`, `description`) VALUES (2, 'Paga');
INSERT INTO `Xl3R7tru__asaas`.`charges_status` (`id`, `description`) VALUES (3, 'Vencida');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Xl3R7tru__asaas`.`companies`
-- -----------------------------------------------------
START TRANSACTION;
USE `Xl3R7tru__asaas`;
INSERT INTO `Xl3R7tru__asaas`.`companies` (`id`, `name`, `cpf_cnpj`) VALUES (1, 'Revers Drevers Company', '12345678911');

COMMIT;

